### ISSUE TITLE
Dar de alta dispositivos

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#1]
## Identificador
_HU-1001_

## Descripción
**Como** Administrador **puedo** dar de alta dispositivos **para** agregarlos a la lista de inventario.

## Conversación
Algunos dispositivos requieren ser registrados con su número de serie. Para otros dispositivos este campo no aplica: Ubicación del dispositivo (Aulas).

## To-Do
- [x] Base de datos con entidades Administrador y Dispositivo
- [x] Dar de alta un administrador en la base de datos
- [x] Diseñar la página de inicio de sesión
- [x] Diseñar la página de "alta de dispositivos"
- [x] Pasar el diseño de la página a código
- [x] Codificar la lógica interna

## Criterios de Aceptación
En pantalla aparecerá una notificación indicando que la operación tuvo éxito. Los dispositivos añadidos aparecerán dentro del catálogo del sitio web.

## Relaciones
_NA_
