### ISSUE TITLE
Estados de préstamos

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#10]
## Identificador
_HU-1010_

## Descripción
Como Administrador puedo actualizar el estado de préstamo de un dispositivo para registrarlo como recibido. 

## Conversación
El administrador deberá realizar esta acción durante la recolección física del dispositivo. 

## To-Do
- [x] Refinar el diseño de la página en base al prototipo
- [x] Pasar el diseño a código.
- [x] Establecer una convención de etiquetado para identificar el estado de un préstamo.
- [x] Crear lógica interna para procesar las etiquetas y que estas se vean reflejadas en los préstamos.
- [x] Crear lógica interna para asignar etiquetas de estados a los préstamos desde la vista del administrador.

## Criterios de Aceptación
Una notificación aparecerá en pantalla, indicando que el dispositivo ya se registró como entregado. El administrador será redireccionado a la lista de reservaciones donde aparecerá el estado del préstamo actualizado. 

## Relaciones
_ID: HU-1009_
