### ISSUE TITLE
Profesor solicita préstamo de dispositivo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#12]
## Identificador
_HU-2002_

## Descripción
**Como** Profesor **puedo** hacer reservaciones de dispositivos **para** apartar los dispositivos y poder utilizarlos.

## Conversación
El profesor podrá observar las fechas dentro de las cuales no puede hacer la reservación del dispositivo.

## To-Do
- [x] Reutilizar la vista de "reservación" usada por el administrador de laboratorio
- [x] En la sección de "Detalles del dispositivo" (ubicado en la parte izquierda) elliminar la opción que muestra los números de serie del dispositivo
- [x] En la sección de "Detalles del dispositivo" (ubicado en la parte izquierda) Agregar un campo de "Etiquetas" donde se desplieguen todas las etiquetas que pertenecen a este dispositivo

## Criterios de Aceptación
Después de haber seleccionado un dispositivo del catálogo se seleccionan las fechas de inicio y fin de la reservación disponibles y se permite realizar la reserva 

## Relaciones
ID: _HU-1005_
