### ISSUE TITLE
Profesor visualiza solicitud de préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#13]
## Identificador
_HU-2003_

## Descripción
**Como** Profesor **puedo** ver mi solictud de préstamo de dispositivos **para** monitorear el estado de mi solicitud y revisar los detalles de la misma. 

## Conversación
El profesor puede buscar sus solicitudes de préstamo mediante un ID 

## To-Do
- [x] El usuario llegará a la vista mediante el vínculo "Préstamos"
- [x] Pasar el diseño de la vista de "Préstamos a HTML"
- [x] Crear una barra de búsqueda que exitósamente traiga los detalles de una solicitud de reservación a partir de un ID
- [x] Cargar los detalles de una solicitud de reservación debajo de la barra de búsqueda
- [x] Crear una vista con un mensaje que indique cuando una solicitud de préstamo no se haya encontrado

## Criterios de Aceptación
- El profesor al ingresar el ID de su solicitud de préstamo, será redirigido a una página donde contiene los detalles de dicha reservación

## Relaciones
ID: _HU-1007_
