### ISSUE TITLE
Profesor recibe email de responsabilidad de préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#14]
## Identificador
_HU-2004_

## Descripción
**Como** Profesor **puedo** recibir un correo electrónico que indica que he sido referido como profesor responsable en el préstamo de un dispositivo solicitado por un alumno, **para** ver quien es el alumno que está haciendo la solicitud y qué dispositivo está pidiendo.

## Conversación
El correo contendrá el nombre del estudiante, el nombre del dispositivo prestado, y la cantidad de dispositivos prestados.

## To-Do
- [x] Realizar el diseño del correo con la información sobre el alumno y el dipositivo que se esta solicitando
- [x] Pasar el diseño del correo a codigo para ser usado por el mailer
- [x] Activar el mailer para enviar un correo al profesor cuando un alumno crea una soolicitud de prestamo
- [x] Se habilita la posibilidad de hacer click en las opciones para aprobar o rechazar el correo

## Criterios de Aceptación
El profesor recibirá un correo mandado por el sistema con la solicitud del estudiante. 

## Relaciones
ID: _HU-3002_
