### ISSUE TITLE
Profesor acepta o rechaza responsabilidad de préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#15]
## Identificador
_HU-2005_

## Descripción
**Como** Profesor **puedo** aceptar o rechazar ser profesor responsable en el préstamo de un dispositivo solicitado por un alumno, **para** prohibir al alumno hacer una reserva incorrecta o innecesaria.

## Conversación
El correo contendrá el nombre del estudiante, el nombre del dispositivo prestado, y la cantidad de dispositivos prestados.

## To-Do
- [x]  Redicionamiento desde las opciones de "Aprobar" o "Rechazar" del correo electronico
- [x] Realizar la vista de Aprobar/Rechazar la solicitud de prestamo
- [x] Al hacer click en "Aprobar" se redirecciona hacia una pagina donde aparece un mensaje en que la solicitud fue aceptada.
- [x] Al hacer click en "Rechazar" se redirecciona hacia una pagina donde aparecen un mensaje que la solicitud fue rechazada.

## Criterios de Aceptación
El profesor recibirá un correo mandado por el sistema con la solicitud del estudiante. Al hacer clic en el botón rechazar, el profesor será redireccionado al sitio web con un mensaje indicando que la solicitud de préstamo del alumno ha sido denegada.

## Relaciones
ID: _HU-3005_
