### ISSUE TITLE
Profesor modifica solicitud de préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#16]
## Identificador
_HU-2006_

## Descripción
**Como** Profesor **puedo** modificar mis solicitudes de préstamo **para** utilizar una cantidad diferente de dispositivos o modificar alguna fecha de la reservación. 

## Conversación
El profesor no puede modificar la solicitud de préstamo de un alumno, este debe hacerse responsable de hacer el cambio. 

## To-Do
- [x] En la vista de "Préstamos" agregar botones al final del detalle de la solictud de préstamo con las acciones: "Modificar" y "Cancelar solicitud"
- [ ] Crear un modal que confirme la acción de cancelar una solicitud
- [ ] Crear scripts y queries para que se cancele la solicitud de préstamo a petición del usuario
- [ ] Mostrar los botones "Guardar" y "Salir sin cambios" al momento de hacer click sobre "Modificar".  Se deberán de ocultar los botones "Modificar" y "Cancelar solicitud"
- [ ] Crear scripts y queries para que los campos que sean editados, se cambien en la base de datos
- [ ] Una vez cargada una solicitud de préstamo agregar el mensaje: "Si deseas que tu solicitud incluya más dispositivos, deberás de cancelarla y volver a crear otra solicitud"

## Criterios de Aceptación
El profesor ingresará a la página y utilizará su código de reservación para modificar la cantidad de dispositivos solicitados. 

## Relaciones
ID: _HU-1006_
