### ISSUE TITLE
Profesor recibe email con confirmación de préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#17]
## Identificador
_HU-2007_

## Descripción
**Como** Profesor **puedo** recibir correos electrónicos con la confirmación de mi solicitud de préstamo, **para** conocer si mi solicitud fue aprobada o rechazada. 

## Conversación
NA

## To-Do
- [x] Activar el mailer para que envíe un correo electrónico cuando el profesor haya hecho una solicitud de préstamo
- [x] Pasar el diseño, del contenido correo electrónico, a código
- [x] Activar el mailer para que envíe un correo electrónico cuando una solicitud de préstamo sea aprobada
- [x] Pasar el diseño, del contenido de correo electrónico con la actualización, a código

## Criterios de Aceptación
Una vez que el Administrador del laboratorio haya aprobado o rechazado la solicitud de un profesor, el profesor recibirá un correo electrónico indicando el estado de su solicitud. 

## Relaciones
ID: _HU-2002_
