### ISSUE TITLE
Modificar detalles de dispositivo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#2]
## Identificador
_HU-1002_

## Descripción
**Como** Administrador **puedo** dar de baja dispositivos **para** quitarlo por haberse vuelto obsoleto.

## Conversación:
Algunas razones por las cuales se da de baja un dispositivo son: 
- Dispositivo obsoleto 
- Dispositivo perdido

## To-Do
- [x] Sección donde se pueda añadir un dispositivo en específico (en caso de que este cuente con un número de serie) a una de las siguientes categorías: mermas (obsoleto), En reparación, Dondado, Perdido
- [x] Sección donde se pueda añadir números de serie a un dispositivo que anteriormente no los tenía.
- [x] Sección donde se puedan editar (añadir o eliminar) las etiquetas que tiene un dispositivo.

## Criterios de Aceptación
En pantalla aparecerá una notificación indicando que la operación tuvo éxito. Los cambios hechos a los dispositivos modificados se reflejarán en la página correspondiente de "detalles".

## Relaciones
ID: _HU-1001_
