### ISSUE TITLE
Alumno recibe email con confirmación de préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#23]
## Identificador
_HU-3005_

## Descripción
**Como** Alumno **puedo** recibir correos electrónicos con la confirmación de mi solicitud de préstamo, **para** conocer si mi solicitud fue aprobada o rechazada. 

## Conversación
NA

## To-Do
- [x] Realizar el diseño, del contenido correo electrónico a código
- [x] Pasar el diseño del correo a codigo
- [x] Activar el mailer para que envíe un correo electrónico al alumno cuando la solicitud de prestamo haya sido confirmada o rechazada 

## Criterios de aceptación
Una vez que el Administrador del laboratorio haya aprobado o rechazado la solicitud de un profesor, el alumno recibirá un correo electrónico indicando el estado de su solicitud. 

## Relaciones
_ID: HU-3002_
