### ISSUE TITLE
Alumno recibe email con recordatorio de entrega

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#24]
## Identificador
_HU-3006_

## Descripción
**Como** Alumno **puedo** recibir correos electrónicos con un recordatorio **para** entregar un dispositivo prestado, para evitar entregar el dispositivo tarde. 

## Conversación
NA

## To-Do
- [x] Realizar el diseño de correo electronico con la información necesaria
- [x] Pasar el diseño del correo al codigo de mailer
- [x] A medianoche de cada día, el sistema verificará cuales entregas están a 1 día de expirar . A dichos solicitantes enviará un email

## Criterios de aceptación
Si el sistema detecta que un dispositivo no ha sido entregado, el alumno recibirá automáticamente un correo electrónico indicando que aún no ha entregado el dispositivo prestado. 

## Relaciones
_ID: HU-3002, HU-3005_
