### ISSUE TITLE
Entradas de usuario en la vista "Altas de Dispositivos"

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#25]
## Identificador
_TASK-0001_
  
## Descripción
Dentro de la vista donde el administrador de laboratorio da de alta dispositivos nuevos, se requiere de añadir elementos adicionales a los scripts que manejan las entradas de usuario en el formulario. 

## To-Do
- [x] La entrada _Etiquetas_ puede estar vacía
- [x] Convertir a minúsculas (`tolower`) todos las etiquetas (_tags_) para evitar crear más de una con el mismo nombre.
- [x] Agregar script al checkbox de "_Se requiere No. de serie_" para que oculte la entrada de usuario (textbox) "_Número de serie_" cuando no esté seleccionado.

## Criterios de Aceptación
- El agregar un dispositivo con dos tags que solo varían en mayúsculas (ejemplo: _android_ y _Android_) no deberá de generar dos tags distintas en la base de datos.
- El Cuando el checkbox de "Se requiere No. de Serie"  está seleccionado, muestra el _textbox_ de "No. de Serie", y cuando no está seleccionado oculta el _textbox_

## Relaciones
ID: _HU-1001_
