### ISSUE TITLE
Recomendación para autocompletar formulario de alta de dispositivos

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#26]
## Identificador
 TASK-0002
 
## Descripción
Acualmente el administrador de laboratorio al dar de alta un dispositivo tiene que llenar todo el formulario. Se desea que haya una opción de autocompletar, donde conforme vaya escribiendo dentro de un _textbox_, inmediatamente en la parte de abajo aparezca una lista de nombres relacionados para evitar que escriba el nombre de un producto de dos maneras distintas.

## To-Do
- [x] Dropdown que recomiende nombres de dispositivos previamente agregados, para el textbox de _Nombre_
- [x] Dropdown que recomiende marcas de dispositivos previamente agregadas, para el textbox de _Marca_
- [x] Dropdown que recomiende modelos de dispositivos previamente agregados, para el textbox de _Modelo_

## Criterios de Aceptación
- Para cualquiera de los campos: "Nombre", "Marca" o "Modelo". Deberá de aparecer un dropdown con las recomendaciones para automáticamente autocompletar el campo donde se esté escribiendo al momento de hacer click sobre una de ellas.

## Relaciones
ID: _HU-1001_
