### ISSUE TITLE
Barra de búsqueda de dispositivos

### ISSUE THREAD

**Issue by abelardogzz** [ProyectoIntegrador2018/Inventarios#29]
## Identificador
TASK-0005
  
## Descripción
Feature para implementar la funcionalidad de busuqeda de distintas maneras dentro de los dispositivos registrados en el sistema

## To-Do
- [x] Agregar una barra de búsqueda que funcione por nombre
- [x] Agregar una barra de búsqueda que funcione por marca
- [x] Agregar una barra de búsqueda que funcione por modelo
- [x] Agregar una barra de búsqueda que funcione por tags
- [x] Quitar el "Lorem Ipsum" de la descripcion del dispositivo

## Criterios de Aceptación
- Se pueden buscar dispositivos por cada una de las categorías y no existe mas texto en Lorem Ipsum

## Relaciones
NA
