### ISSUE TITLE
Consulta de inventario

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#3]
## Identificador
_HU-1003_

## Descripción
**Como** Administrador **puedo** consultar dispositivos registrados en el catálogo **para** conocer el estado del inventario del laboratorio.

## Conversación
Cada dispositivo deberá de desplegar la siguiente información: 
- Nombre del dispositivo 
- Marca 
- Cantidad de dispositivos disponibles a la fecha 
- Deseable pero no requisito, una imagen del dispositivo.

## To-Do
- [x] Base de datos con Dispositivo
- [x] Diseñar la página de "Inventario"
- [x] Pasar el diseño de la página a código
- [x] Codificar la lógica interna

## Criterios de Aceptación
Al ir a la sección de catálogo de dispositivos, aparecerán en pantalla los dispositivos registrados en el inventario.

## Relaciones
ID: _HU-1001_, _HU-1002_
