### ISSUE TITLE
Pagina de Inicio

### ISSUE THREAD

**Issue by abelardogzz** [ProyectoIntegrador2018/Inventarios#34]
## Identificador
TASK-0010
  
## Descripción
Hacer un cambio para la pagina de landing, los administradores podran tener acceso a esta pagina y de ahi avanzar a utilizar el sistema

## To-Do
- [x] Hacer la pagina de inicio un "About" del proyecto, 
- [x] Incluir las funciones del proyecto en la pagina de "About"
- [x] Agregar un footer a la pagina de "About" que contenga un enlace para inciar sesion de administrador
- [x] Con el administrador iniciado sesion, la pagina de incio cambia a tener todos los menus de navegación

## Criterios de Aceptación
- Existe una pagina de "About" como inicio
- Existe un enlace para inciar sesion como administrador
- Existe un menu para navegar una vez inciada la sesion

## Relaciones
NA
