### ISSUE TITLE
Cambiar posición de títulos de páginas

### ISSUE THREAD

**Issue by miguelbanda** [ProyectoIntegrador2018/Inventarios#37]
## Identificador
TASK-001
  
## Descripción
Cambiar los títulos de las paginas que tengan el titulo a la izquierda

## To-Do
- [x] Centrar título en página: About
- [x] Centrar título en página: Dar de alta
- [x] Buscar si el título de alguna otra página esta a la izquierda y centrarlo

## Criterios de Aceptación
- Que el titulo aparezca al arriba y en el centro de la pantalla
- Que no se vea afectada la estructura del resto de la página

## Relaciones
NA
