### ISSUE TITLE
Ver solicitudes de reservación

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#4]
## Identificador
_HU-1004_

## Descripción
**Como** Administrador **puedo** ver las reservaciones **para** conocer el estado de los dispositivos prestados.

## Conversación
Las reservaciones pueden tener los siguientes estados: 

- Aprobada (por el administrador) 
- Denegada (por el administrador) 
- Cancelada (por el administrador, o solicitante de la reservación) 
- Pendiente (el solicitante aún no ha ido a recoger el dispositivo) 
- En uso (el solicitante tiene el dispositivo) 
- Tarde (el solicitante no ha entregado el dispositivo) 
- Entregado (el solicitante entregó el dispositivo y está de vuelta en el almacén) 
- Entregado tarde

## To-Do
- [x] Base de datos con entidades Dispositivo y Préstamo/Reservación
- [x] Diseñar la página de "Lista de Reservaciones"
- [x] Pasar el diseño de la página a código
- [x] Implementar la consulta de reportes

## Criterios de Aceptación
Al ir a la sección de reservaciones, aparecerán en pantalla una lista con el nombre del solicitante, matrícula/nómina, dispositivo pedido, cantidad, número de serie y estado de la reservación.

##Relaciones:
ID: _HU-1005_
