### ISSUE TITLE
Cambiar el estado de un préstamo

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#41]
## Identificador
TASK-0011
  
## Descripción
< Cómo administrador puedo cambiar el estado de un préstamo para ir cambiando entre las etapas en las que este se encuentra. >

## To-Do
- [x] Hacer llamada para cuando se hace clic en el botón de cambio de estado del préstamo.
- [x] Crear función de cambio de préstamo en el controlador de préstamos.
- [x] Implementar y probar método de cambio de estado.

## Criterios de Aceptación
- < El estado del préstamo cambiará correctamente en el orden de estados de este. >

## Relaciones
< ID de la historia de usuario a la que está relacionada u a otro task. Si no aplica poner: NA >
ID: _HU-1007_
