### ISSUE TITLE
Establecer una sintaxis para el nombramiento de las rutas

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#46]
## Identificador
TASK-0012
  
## Descripción
El nombramiento de las rutas desde el archivo `web.php` debe de uniformizarse de tal modo que se pueda identificar rutas de navegación y llamadas a la base de datos

## To-Do
- [x] Establecer sintaxis para rutas de `AboutController.php`.
- [x] Establecer sintaxis para rutas de `DeviceController.php`.
- [x] Establecer sintaxis para rutas de `HomeController.php`.
- [x] Establecer sintaxis para rutas de `InventoryController.php`.
- [x] Establecer sintaxis para rutas de `LoanController.php`.

## Criterios de Aceptación
Se puede distinguir cuales son las rutas de:
- Navegación
- Acceso a la base de datos
- Modificación a la base de datos

## Relaciones
NA
