### ISSUE TITLE
Establecer una sintaxis para el nombramiento de las funciones de los controladores

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#47]
## Identificador
TASK-0013
  
## Descripción
El nombramiento de las funciones para cada controlador, dentro de la carpeta `app/Http/Controllers` , debe de uniformizarse de tal modo que se pueda identificar si son funciones de modificación, acceso, o de vistas.

## To-Do
- [x] Establecer sintaxis para funciones de `AboutController.php`.
- [x] Establecer sintaxis para funciones de `DeviceController.php`.
- [x] Establecer sintaxis para funciones de `HomeController.php`.
- [x] Establecer sintaxis para funciones de `InventoryController.php`.
- [x] Establecer sintaxis para funciones de `LoanController.php`.

## Criterios de Aceptación
Se puede distinguir cuales son funciones de:
- Accesso
- Modificación
- Control de vistas

## Relaciones
NA
