### ISSUE TITLE
Reservación de dispositivos

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#5]
## Identificador
_HU-1005_

## Descripción
**Como** Administrador **puedo** hacer una reservación de un dispositivo **para** un evento académico del organizado por el Tecnológico de Monterrey.

## Conversación
A diferencia de profesores o alumnos donde la solicitud de reservación debe ser aprobada, cuando un administrador realiza una reservación esta es automáticamente aprobada.

## To-Do
- [x] Crear base de datos con entidad Préstamo/Reservación
- [x] Diseño de la página "Creación de reservación"
- [x] Pasar el diseño de la página a código
- [x] Impementar la creación de reservación

## Criterios de Aceptación
El administrador será redirigido a la página de reservaciones donde aparecerá en la lista la reservación de dispositivos que realizó.

## Relaciones
_NA_
