### ISSUE TITLE
Validación del formulario de solicitud de préstamo

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#50]
## Identificador
TASK-0016
  
## Descripción
Se requieren de nuevas validaciones para cuando un administrador, profesor o alumno, llene una nueva solicitud de préstamo.

## To-Do
- [x] Validar que para profesores la nómina empiece con _'L'_ seguido de al menos 8 dígitos.
- [x] Validar que para alumnos la matrícula empiece con _'A'_ seguido de al menos 8 dígitos
- [x] Validar que para profesores y alumnos el correo electrónico sea institucional: _@itesm.mx_, o _@tec.mx_
- [x] Cambiar el label del textbox de email a _Correo institucional_
- [x] Validar que para alumnos el correo electrónico coincida con su matrícula

## Criterios de Aceptación
La página muestra errores al usuario cuando:
- Un profesor o adminstrador ingresa una nómina errónea
- Un estudiante ingresa una matrícula errónea
- Un administrador, profesor o estudiante ingresa un correo electrónico no institucional
- Un estudiante ingresa un correo institucional distinto al que le corresponde en su matrícula.

## Relaciones
NA
