### ISSUE TITLE
Reportes de solicitudes de préstamo

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#51]
## Identificador
TASK-0017
  
## Descripción
Se necesitan añadir filtros adicionales a la sección de _"Reportes"_ que ayuden al administrador a crear reportes más específicos.

## To-Do
- [x] Los archivos .CSV generados, deben contener encabezados que describan el contenido de las columnas.
- [x] Añadir la opción para generar un reporte relacionado a solicitudes.
- [x] Añadir un datepicker, donde el administrador elija el rango de fechas que el reporte cubrirá.
- [x] Añadir una lista de checkboxes donde el administrador elija los tipos de solicitudes de préstamo que se mostrarán en el reporte.
- [x] Añadir una lista de checkboxes donde el administrador elija filtrar las solicitudes de: alumnos, profesores o ambos.

## Criterios de Aceptación
- Existe una pantalla donde se le presenta al administrador diversos filtros para generar reportes.
- El administrador genera reportes específicos selecccionando los filtros y dando click en el botón "Descargar Reporte".
- Los filtros tienen una valor seleccionado por defecto 

## Relaciones
ID: _HU-1008_
