### ISSUE TITLE
Modificar UI de "Alta de dispositivos"

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#52]
## Identificador
TASK-0018
  
## Descripción
El formulario para dar de alta dispositivos, tarda en cargar las sugerencias para rellenar los campos de nombre, marca y modelo. Se requiere añadir un delay que permita a la página cargar primero las listas de sugerencias, para que funcione de manera rápida el autocompletado.

## To-Do
- [x] Agregar un **_delay_** al momento de cargar la página, para dar tiempo a las listas de autocompletado de obtener los datos.
- [x] Agregar un **_loader spinner_** para simular que la página esta cargando
- [x] Cambiar el **texto de fondo** del `text-area` a: _"Ingrese No. de Serie separado por comas"_ .

## Criterios de Aceptación
- Al visitar la página "alta de dispositivos", se muestra la página vacía con un _spinner_ que indica que se está "cargando". 
- Al terminar la simulación de carga, se despliega la página con el formulario completo
- La función de autocompletado para los campos de: nombre, marca y modelo, debe de mostrar las sugerencias en menos de 0.5 segundos.
- El texto de fondo en el text area menciona que se deben de separar por comas los números de serie.

## Relaciones
ID: _HU-1001_
