### ISSUE TITLE
Agregar un diccionario de estados

### ISSUE THREAD

**Issue by guillermoAMS** [ProyectoIntegrador2018/Inventarios#53]
## Identificador
TASK-0019
  
## Descripción
Actualmente se escribe el código en inglés y se despliega la información al usuario en español. La base de datos almacena los estatus en inglés debido a que los _queries_ son hechos en inglés. Para evitar traducir los datos obtenidos de la base de datos, se creará una variable de tipo diccionario que permita seguir escribiendo los _queries_ en inglés pero almacenando datos en español.

## To-Do
- [ ] Instanciar la variable de tipo diccionario, con el estado en inglés como llave y el estado en español como valor.
- [ ] Modificar los queries a que funcionen utilizando la variable diccionario
- [ ] Eliminar las funciones que traducen los estados del inglés a español y viceversa, de los archivos `.js` y `.blade.php`.
- [ ] Modificar las funciones en los archivos archivos `.js` y `.blade.php`, donde se hayan utilizado las funciones que hacen la traducción a inglés. De tal modo que utilicen la información de manera directa.

## Criterios de Aceptación
- Se cumplen con las pruebas de regresión.
- No se realiza ninguna traducción de estado en el front-end
- Todas las traducciones se realizan en los controladores.
- Las traducciones se realizan utilizando la variable diccionario.

## Relaciones
ID: _HU-1010_
