### ISSUE TITLE
Modificación de reservación

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#6]
## Identificador
_HU-1006_

## Descripción
**Como** Administrador **puedo** modificar una reservación **para** reasignar los dispositivos debido a un incidente de mayor prioridad. 

## Conversación
Al ser una reservación de otra persona, esa persona deberá recibir un correo como notificación para ser informado de que su reservación se vio afectada. 

## To-Do
- [x] Hacer un diseño definido de la página utilizando los prototipos previamente hechos.
- [x] Pasar el diseño a código
- [x] Implementar búsqueda por código de reservación
- [x] Cancelación de reservación
- [x] Crear reservación

## Criterios de Aceptación
El administrador recibirá un mensaje de éxito además que la reservación deberá mostrarse con las nuevas fechas/dispositivos. 

## Relaciones
ID: _HU-1005_, _HU-1007_
