### ISSUE TITLE
Cancelación de reservación

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#7]
## Identificador
_HU-1007_

## Descripción
**Como** Administrador **puedo** cancelar una reservación **para** asignar el dispositivo a un evento de mayor prioridad. 

## Conversación
El administrador no puede cancelar un dispositivo que ya fue entregado. 

## To-Do
- [x] Crear un diseño más refinado a partir de los prototipos
- [x] Pasar el diseño a código
- [x] Reutilizar búsqueda por número de reservación.
- [x] Implementar método para cancelar un préstamo.

## Criterios de Aceptación
Aparecerá una pantalla modal para comprobar la acción. Si se prosigue, el administrador será redirigido a la lista de reservaciones actualizada. 

## Relaciones
ID: _HU-1005_, _HU-1006_
