### ISSUE TITLE
Generación de reportes

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#8]
## Identificador
_HU-1008_

## Descripción
**Como** Administrador **puedo** generar reportes de los préstamos del inventario **para** conocer los dispositivos más solicitados. 

## Conversación
Los reportes servirán como información para el administrador y los profesores que soliciten reportes al administrador. 

## To-Do
- [x] Crear en código HTML la vista relacionada a la generación de reportes
- [x] Crear queries para obtener la lista de inventario.
- [x] Generar un archivo .CSV con los datos obtenidos del reporte de inventario.
- [x] Crear querie para obtener la lista de préstamos dentro de un rango de fechas definidas por el administrador de laboratorio.
- [x] Generar un archivo .CSV con los datos obtenidos del reporte de préstamos.

## Criterios de Aceptación
Un reporte generado en formato .CSV se abrirá en la pestaña del explorador. 

## Relaciones
ID: _HU-1003_, _HU-1004_
