### ISSUE TITLE
Registro de entrega de dispositivos

### ISSUE THREAD

**Issue by larsrojo** [ProyectoIntegrador2018/Inventarios#9]
## Identificador
_HU-1009_

## Descripción
**Como** Administrador **puedo** registrar la entrega de un dispositivo a un alumno/profesor **para** que el sistema actualice la base de datos de dispositivos disponibles. 

## Conversación
El administrador deberá realizar esta acción durante la entrega física del dispositivo. 

## To-Do
- [x] Refinar el diseño del prototipo
- [x] Pasar el diseño a código
- [x] Módulo para marcar un préstamo como entregado

## Criterios de Aceptación
El estado del dispositivo ahora aparece como entregado en el sistema. 

## Relaciones
ID: _HU-1005_
